name: validate-changes
on: [push]
jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run validation
        id: validation
        uses: pbzona/ld_data_validator@v0.25
      - name: Get the output time
        run: echo "The time was ${{ steps.validation.outputs.time }}"
      - name: Get the triggering event
        run: echo "${{ steps.validation.outputs.event }}"
      - name: Get the modified files
        run: echo "${{ steps.validation.outputs.filesChanged }}"
      - name: Get the modified flags
        run: echo "${{ steps.validation.outputs.flagsChanged }}"
      - name: Get the flag modification
        run: echo "${{ steps.validation.outputs.flagModifications }}"